use crate::span::Span;

#[derive(Debug, Clone, PartialEq)]
pub struct Token {
    pub kind: TokenKind,
    pub span: Span,
}

impl Token {
    pub fn new(kind: TokenKind, start: usize, end: usize) -> Self {
        Self {
            kind,
            span: Span::new(start, end),
        }
    }
}

#[derive(Debug, Clone, PartialEq)]
pub enum TokenKind {
    Ident(String),
    Int(String),
    Float(String),
    String(String),
    Char(String),
    Keyword(Keyword),
    At,
    Dot,
    Comma,
    Colon,
    Semicolon,
    Arrow,
    FatArrow,
    LParen,
    RParen,
    LBrace,
    RBrace,
    LBracket,
    RBracket,
    Lt,
    Gt,
    Amp,
    AmpAmp,
    AmpEq,
    Star,
    StarEq,
    Caret,
    Question,
    Plus,
    PlusEq,
    Minus,
    MinusEq,
    Slash,
    SlashEq,
    Percent,
    PercentEq,
    Eq,
    EqEq,
    Bang,
    BangEq,
    Le,
    Ge,
    LtLt,
    GtGt,
    LtLtEq,
    GtGtEq,
    Pipe,
    PipePipe,
    PipeEq,
    Newline,
    Eof,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Keyword {
    Async,
    Await,
    Break,
    Const,
    Continue,
    Else,
    Enum,
    Extern,
    False,
    Fn,
    For,
    If,
    Impl,
    Import,
    In,
    Interface,
    Let,
    Match,
    Module,
    Mut,
    Pub,
    Return,
    Self_,
    Static,
    Struct,
    Test,
    True,
    Type,
    Unsafe,
    Use,
    While,
    Move,
}

impl Keyword {
    pub fn from_ident(ident: &str) -> Option<Self> {
        Some(match ident {
            "async" => Self::Async,
            "await" => Self::Await,
            "break" => Self::Break,
            "const" => Self::Const,
            "continue" => Self::Continue,
            "else" => Self::Else,
            "enum" => Self::Enum,
            "extern" => Self::Extern,
            "false" => Self::False,
            "fn" => Self::Fn,
            "for" => Self::For,
            "if" => Self::If,
            "impl" => Self::Impl,
            "import" => Self::Import,
            "in" => Self::In,
            "interface" => Self::Interface,
            "let" => Self::Let,
            "match" => Self::Match,
            "module" => Self::Module,
            "mut" => Self::Mut,
            "pub" => Self::Pub,
            "return" => Self::Return,
            "self" => Self::Self_,
            "static" => Self::Static,
            "struct" => Self::Struct,
            "test" => Self::Test,
            "true" => Self::True,
            "type" => Self::Type,
            "unsafe" => Self::Unsafe,
            "use" => Self::Use,
            "while" => Self::While,
            "move" => Self::Move,
            _ => return None,
        })
    }
}

impl TokenKind {
    pub fn display(&self) -> String {
        match self {
            TokenKind::Ident(value)
            | TokenKind::Int(value)
            | TokenKind::Float(value)
            | TokenKind::String(value)
            | TokenKind::Char(value) => value.clone(),
            TokenKind::Keyword(keyword) => format!("{keyword:?}"),
            TokenKind::At => "@".into(),
            TokenKind::Dot => ".".into(),
            TokenKind::Comma => ",".into(),
            TokenKind::Colon => ":".into(),
            TokenKind::Semicolon => ";".into(),
            TokenKind::Arrow => "->".into(),
            TokenKind::FatArrow => "=>".into(),
            TokenKind::LParen => "(".into(),
            TokenKind::RParen => ")".into(),
            TokenKind::LBrace => "{".into(),
            TokenKind::RBrace => "}".into(),
            TokenKind::LBracket => "[".into(),
            TokenKind::RBracket => "]".into(),
            TokenKind::Lt => "<".into(),
            TokenKind::Gt => ">".into(),
            TokenKind::Amp => "&".into(),
            TokenKind::AmpAmp => "&&".into(),
            TokenKind::AmpEq => "&=".into(),
            TokenKind::Star => "*".into(),
            TokenKind::StarEq => "*=".into(),
            TokenKind::Caret => "^".into(),
            TokenKind::Question => "?".into(),
            TokenKind::Plus => "+".into(),
            TokenKind::PlusEq => "+=".into(),
            TokenKind::Minus => "-".into(),
            TokenKind::MinusEq => "-=".into(),
            TokenKind::Slash => "/".into(),
            TokenKind::SlashEq => "/=".into(),
            TokenKind::Percent => "%".into(),
            TokenKind::PercentEq => "%=".into(),
            TokenKind::Eq => "=".into(),
            TokenKind::EqEq => "==".into(),
            TokenKind::Bang => "!".into(),
            TokenKind::BangEq => "!=".into(),
            TokenKind::Le => "<=".into(),
            TokenKind::Ge => ">=".into(),
            TokenKind::LtLt => "<<".into(),
            TokenKind::GtGt => ">>".into(),
            TokenKind::LtLtEq => "<<=".into(),
            TokenKind::GtGtEq => ">>=".into(),
            TokenKind::Pipe => "|".into(),
            TokenKind::PipePipe => "||".into(),
            TokenKind::PipeEq => "|=".into(),
            TokenKind::Newline => "\\n".into(),
            TokenKind::Eof => "<eof>".into(),
        }
    }
}
